const mongoose = require("mongoose");
const { Schema, model } = mongoose;

const bookingSchema = new Schema(
  {
    // we want to reference users inside the listing model and for that we will use their IDs
    // this is telling us that in "user" property of each listing object, we will have
    // saved ObjectId (id that is automatically generated by MongoDB) that belongs to one of the users from the users collection
    user: { type: Schema.Types.ObjectId, ref: "user" },
    listing: { type: Schema.Types.ObjectId, ref: "listing" },
    startDate: { type: Date, required: [true, "A start date is required"] },
    endDate: { type: Date, required: [true, "An end date is required"] },
    paymentMethod: {
      type: String,
      required: [true, "Please enter a payment method"]
    }
  },
  {
    timestamps: true
  }
);

module.exports = model("Booking", bookingSchema);
