const mongoose = require('mongoose');
const { Schema, model } = mongoose;

const listingSchema = new Schema(
  {
    // unless you are defining more than the "type" property, you don't have to use {} (see below)
    // firstName: {type: String, require: true}
    title: String,
    brand: String,
    size: ,
    condition: ,
    category: ,
    color: { type: Schema.Types.ObjectId, ref: 'listingColor' },
    ,
    description: String,
    // we want to reference users inside the listing model and for that we will use their IDs
    // this is telling us that in "user" property of each listing object, we will have
    // saved ObjectId (id that is automatically generated by MongoDB) that belongs to one of the users from the users collection
    user: { type: Schema.Types.ObjectId, ref: 'user' },
    price: { type: Number }, // find out how to make it 2 decimals for price
    rating: Number // v2
  },
  {
    timestamps: true
  }
);

// const user = model('user', userSchema);
// module.exports = user;

module.exports = model('Listing', listingSchema);
